container:
  image: gradle:4.4.1-jdk8
  cpu: 4
  memory: 11G

no_caching_task:
  dist_script: gradle dist --no-build-cache

global_caching_task:
  gradle_cache:
    folder: ~/.gradle/caches
  dist_script: gradle dist --no-build-cache
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete

build_cache_task:
  gradle_cache:
    folder: ~/.gradle/caches
  dist_script: gradle dist
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete