container:
  image: java:8-jdk
  cpu: 8
  memory: 20G

no_caching_task:
  test_script: ./gradlew test

global_caching_task:
  gradle_cache:
    folder: ~/.gradle/caches
  test_script: ./gradlew test
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete

build_cache_cold_task:
  gradle_cache:
    folder: ~/.gradle/caches
  test_script: ./gradlew test --build-cache
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete

build_cache_warm_task:
  depends_on: build_cache_cold
  gradle_cache:
    folder: ~/.gradle/caches
  test_script: ./gradlew test --build-cache
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete